Algoritmo "circulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2023
Var

raio, area : real
 
Inicio

escreva("Digite o valor do raio do círculo: ")
leia(raio)

area <- pi * exp(raio, 2)

escreva(area)








Fimalgoritmo