Algoritmo "consumo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2023
Var

 distancia, combustivel, media : real


 
Inicio

escreva("Distancia percorrida: ")
leia(distancia)
escreva("Combustível gasto: ")
leia(combustivel)

media <- distancia  / combustivel
escreval("Consumo medio =", media:8:3)

Fimalgoritmo