Algoritmo "medidas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2023
Var



 
Inicio

 escreval ("Digite a quantidade de segundos")
 leia(quantidade)
 
 segundos <- quantidade % 60
 minutos <- quantidade \ 60
 
 escreval (horas, ":", minutos, ":", segundos)



Fimalgoritmo