Algoritmo "Soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2023
Var

 x, y, soma : inteiro
Inicio

 escreva("Diga o Valor de x = ")
 leia(x)
 escreva("Diga o Valor de y = ")
 leia(y)
 
 soma <- x + y
 
 escreva("A soma de", x, " e ", y, " é igual a ", soma, "!")








Fimalgoritmo